module.exports = {
  apps: [
    {
      name: 'alti-team-mcp-server',
      script: 'src/mcp-server/index.ts',
      interpreter: 'ts-node',
      interpreterArgs: '--esm --loader ts-node/esm',
      instances: 1,
      autorestart: true,
      watch: false,
      max_memory_restart: '500M',
      env: {
        NODE_ENV: 'development',
        USE_POSTGRES: 'false',
        PORT: 3000,
      },
      env_production: {
        NODE_ENV: 'production',
        USE_POSTGRES: 'true',
        PORT: 3000,
        DB_HOST: process.env.DB_HOST || 'localhost',
        DB_PORT: parseInt(process.env.DB_PORT || '5432'),
        DB_USER: process.env.DB_USER || 'alti_team',
        DB_PASSWORD: process.env.DB_PASSWORD || 'password123',
        DB_NAME: process.env.DB_NAME || 'alti_team',
        NEXTAUTH_SECRET: process.env.NEXTAUTH_SECRET,
        NEXTAUTH_URL: process.env.NEXTAUTH_URL || 'http://localhost:3000',
      },
      log_file: 'logs/combined.log',
      out_file: 'logs/out.log',
      error_file: 'logs/error.log',
      log_date_format: 'YYYY-MM-DD HH:mm:ss Z',
      merge_logs: true,
      kill_timeout: 5000,
      restart_delay: 1000,
      max_restarts: 10,
      min_uptime: '10s',
    },
  ],
}
